---
# tasks file for webserver

- name: install apache
  become_user: root
  become: yes
  ansible.builtin.apt:
    name: "apache2"
    state: present

- name: remove html folder
  become_user: root
  become: yes
  ansible.builtin.command: rm -r /var/www/html

- name: install git
  become_user: root
  become: yes
  ansible.builtin.apt:
    name: "git"
    state: present

- name: clone a repo
  become_user: root
  become: yes
  ansible.builtin.git:
    repo: https://github.com/oxblixxx/news-homepage-main.git
    dest: /var/www/html
    force: yes

- name: Start service httpd, if not started
  become_user: root
  become: yes
  ansible.builtin.service:
    name: apache2
    state: started
